### ISSUE TITLE
Thank you & Plans for Melpa?

### ISSUE THREAD

**Issue by Zaijab** [ml729/calfw-blocks#3]
Aloha @ml729,

Thank you so much for this package, it works wonderfully. It really helps me visualize my task lists for the day. I hope this package gets more recognition. I believe other people may find it useful as well. Are there plans to upload to MELPA?

In case anyone wants to use this package on Guix here is a package definition

```
(define-public emacs-calfw-blocks
  (package
    (name "emacs-calfw-blocks")
    (version "d72e95bf47999df98684c0d602adee6abc4bcb17")
    (source (origin
	      (method git-fetch)
	      (uri (git-reference
		    (url "https://github.com/ml729/calfw-blocks.git")
		    (commit version)))
	      (file-name (git-file-name name version))
	      (sha256
	       (base32
		"1p2yqp9s2p1rk3z2d09lzy8dimn2rwdf5qxajhq6jms0315dyggs"))))
    (build-system emacs-build-system)
    (propagated-inputs
     (list 
      `("emacs-calfw" ,(specification->package "emacs-calfw"))))
    (home-page "https://github.com/ml729/calfw-blocks")
    (synopsis "Visual time blocks for the Emacs Calendar Framework (calfw).")
    (description "Visual time blocks for the Emacs Calendar Framework (calfw).")
    (license license:gpl3+)))
```

Mahalo.

**Comment by ml729** [comment]
Thank you @Zaijab for the kind words, I am glad to hear the package is useful for you!
Yes, I think I will try to get it on MELPA, the code has to be tidied up a bit first though (adding docstrings and whatnot). Also, we will have to see if the MELPA maintainers are ok with calfw-blocks overriding and advising many of the original calfw's functions.

**Comment by haji-ali** [comment]
@ml729, I echo the thanks of @Zaijab.

One thing I want to suggest is to add the advices in a minor mode so that they can be enabled/disabled as appropriate.

Also, is the dependancy on `calfw-org` necessary? Or can `calfw-blocks` be used with other `calfw` interfances (like ical for example)?

**Comment by ml729** [comment]
Thanks, I think the suggestion to make a minor mode is great, I'll put it on the todo list (and PRs are also welcome).

For other interfaces, `calfw-blocks` just requires that events are represented as `cfw:event` structs, where `start-time` and `end-time` are set. I checked `calfw-ical` and `calfw-cal`, both satisfy this requirement (but `calfw-howm` looks like it does not), so they should work, although I have not tested them personally. Let me know if you have any issues with them.
