### ISSUE TITLE
Header problem in the source of calfw-blocks

### ISSUE THREAD

**Issue by slyfr** [ml729/calfw-blocks#5]
I would like to install calfw-blocks using use-package. Then I run into the problem that the installation fails because the header of the file is not well formated: it lacks a description.

A fix could to change the first line to 
;;; calfw-blocks.el --- Visual time blocks and more for the Emacs Calendar Framework (calfw) -*- lexical-binding: t; -*-

**Comment by ml729** [comment]
Thanks, I added a description to the header.

**Comment by slyfr** [comment]
Thanks, it works fine now!
